package index

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// Entry holds the annotation metadata for a single file.
type Entry struct {
	Summary     string    `yaml:"summary"`
	Hash        string    `yaml:"hash"`
	Model       string    `yaml:"model"`
	GeneratedAt time.Time `yaml:"generated"`
	Version     int       `yaml:"version"`
}

// Index is the in-memory representation of the llmdoc index file.
type Index struct {
	Files map[string]*Entry `yaml:"files"`
}

// New returns an empty Index.
func New() *Index {
	return &Index{Files: make(map[string]*Entry)}
}

// Load reads an index file from path. Returns a new empty Index if the file
// does not exist yet.
func Load(path string) (*Index, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return New(), nil
		}
		return nil, fmt.Errorf("reading index %s: %w", path, err)
	}

	var idx Index
	if err := yaml.Unmarshal(data, &idx); err != nil {
		return nil, fmt.Errorf("parsing index %s: %w", path, err)
	}
	if idx.Files == nil {
		idx.Files = make(map[string]*Entry)
	}
	return &idx, nil
}

// Save writes the index to path atomically (via a temp file rename).
// Parent directories are created as needed.
func Save(path string, idx *Index) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating index directory: %w", err)
	}

	data, err := yaml.Marshal(idx)
	if err != nil {
		return fmt.Errorf("marshaling index: %w", err)
	}

	header := []byte("# llmdoc index — generated by llmdoc, do not edit manually\n")
	data = append(header, data...)

	// Write to a temp file then rename for atomicity
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0644); err != nil {
		return fmt.Errorf("writing index: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("saving index: %w", err)
	}
	return nil
}
